name: Cache Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔸 Cache step
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm        # Example: caching NPM dependencies
          key: cache-eaf0308  # Cache key as requested

      # 🔸 Print cache result
      - name: prime-cache-eaf0308
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
