name: Cache Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create npm folder
        run: mkdir -p ~/.npm

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-eaf0308

      - name: prime-cache-eaf0308
        run: echo "Cache hit? ${{ steps.cache.outputs.cache-hit }}"
